require:
  - rubocop-minitest
  - rubocop-packaging
  - rubocop-performance

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.5
  Exclude:
    - "*.gemspec"
    - "vendor/**/*"

Layout/SpaceAroundEqualsInParameterDefault:
  EnforcedStyle: no_space

Metrics/AbcSize:
  Exclude:
    - "test/**/*"

Metrics/MethodLength:
  Exclude:
    - "test/**/*"

Metrics/ClassLength:
  Exclude:
    - "test/**/*"

Minitest/MultipleAssertions:
  Max: 6

Naming/MemoizedInstanceVariableName:
  Enabled: false

Style/BarePercentLiterals:
  EnforcedStyle: percent_q

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes
